name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      failAction:
        required: false
        type: boolean
        default: false
        description: Fail Action

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Pass tests
        run: |
          echo "Jojo pr TEST"

      - name: Fail tests
        if: ${{ inputs.failAction }}
        run: |
          exit 1
